baseURL = "https://kan-bayashi.github.io/ParallelWaveGAN/"
languageCode = "en-us"
title = "Unofficial Parallel WaveGAN Implementation Demo"
theme = "paper"

[params]
  AuthorName = "Tomoki Hayashi"
  GithubUser = "kan-bayashi"

[markup.goldmark.renderer]
unsafe= true
